#include "rcc.h"

void RCC_Init(void){
	RCC->CR |= RCC_CR_HSEON;
	while (!(RCC->CR & RCC_CR_HSERDY));

	RCC->CFGR |= RCC_CFGR_PLLSRC_HSE;
	RCC->CFGR &= ~RCC_CFGR_PLLMULL;
	RCC->CFGR |= RCC_CFGR_PLLMULL9;
	RCC->CR |= RCC_CR_PLLON;
	while(!(RCC->CR & RCC_CR_PLLRDY));
	
	RCC->CR &= ~RCC_CR_HSION;
	while((RCC->CR & RCC_CR_HSIRDY));
	
	RCC->CFGR |= RCC_CFGR_HPRE_DIV1;
	RCC->CFGR |= RCC_CFGR_PPRE1_DIV2 | RCC_CFGR_PPRE2_DIV1;
	RCC->CFGR |= RCC_CFGR_ADCPRE_DIV6;
	
	RCC->CFGR |= RCC_CFGR_SW_PLL;
}